name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 18.212.58.95  # Your EC2 instance public IP
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  APP_DIR: /home/ubuntu/app  # Define the app directory as an environment variable

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > mykey.pem
          chmod 600 mykey.pem

      - name: Create app directory on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "mkdir -p $APP_DIR"

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i mykey.pem -r ./* ubuntu@$EC2_PUBLIC_IP:$APP_DIR

      - name: Verify copied files on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "ls -R $APP_DIR"

      - name: Execute deploy script on EC2
        run: |
          ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "cd $APP_DIR && bash deploy.sh"
